<?php

class Enum_HttpStatusCode extends Core_Enum
{
    const HTTP_CONTINUE = 100;
    const HTTP_SWITCHING_PROTOCOLS = 101;
    const HTTP_PROCESSING = 102;
    const HTTP_OK = 200;
    const HTTP_CREATED = 201;
    const HTTP_ACCEPTED = 202;
    const HTTP_NON_AUTHORITATIVE_INFORMATION = 203;
    const HTTP_NO_CONTENT = 204;
    const HTTP_RESET_CONTENT = 205;
    const HTTP_PARTIAL_CONTENT = 206;
    const HTTP_MULTI_STATUS = 207;
    const HTTP_ALREADY_REPORTED = 208;
    const HTTP_IM_USED = 226;
    const HTTP_MULTIPLE_CHOICES = 300;
    const HTTP_MOVED_PERMANENTLY = 301;
    const HTTP_FOUND = 302;
    const HTTP_SEE_OTHER = 303;
    const HTTP_NOT_MODIFIED = 304;
    const HTTP_USE_PROXY = 305;
    const HTTP_RESERVED = 306;
    const HTTP_TEMPORARY_REDIRECT = 307;
    const HTTP_PERMANENTLY_REDIRECT = 308;
    const HTTP_BAD_REQUEST = 400;
    const HTTP_UNAUTHORIZED = 401;
    const HTTP_PAYMENT_REQUIRED = 402;
    const HTTP_FORBIDDEN = 403;
    const HTTP_NOT_FOUND = 404;
    const HTTP_METHOD_NOT_ALLOWED = 405;
    const HTTP_NOT_ACCEPTABLE = 406;
    const HTTP_PROXY_AUTHENTICATION_REQUIRED = 407;
    const HTTP_REQUEST_TIMEOUT = 408;
    const HTTP_CONFLICT = 409;
    const HTTP_GONE = 410;
    const HTTP_LENGTH_REQUIRED = 411;
    const HTTP_PRECONDITION_FAILED = 412;
    const HTTP_REQUEST_ENTITY_TOO_LARGE = 413;
    const HTTP_REQUEST_URI_TOO_LONG = 414;
    const HTTP_UNSUPPORTED_MEDIA_TYPE = 415;
    const HTTP_REQUESTED_RANGE_NOT_SATISFIABLE = 416;
    const HTTP_EXPECTATION_FAILED = 417;
    const HTTP_I_AM_A_TEAPOT = 418;
    const HTTP_MISDIRECTED_REQUEST = 421;
    const HTTP_UNPROCESSABLE_ENTITY = 422;
    const HTTP_LOCKED = 423;
    const HTTP_FAILED_DEPENDENCY = 424;
    const HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL = 425;
    const HTTP_UPGRADE_REQUIRED = 426;
    const HTTP_PRECONDITION_REQUIRED = 428;
    const HTTP_TOO_MANY_REQUESTS = 429;
    const HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE = 431;
    const HTTP_UNAVAILABLE_FOR_LEGAL_REASONS = 451;
    const HTTP_INTERNAL_SERVER_ERROR = 500;
    const HTTP_NOT_IMPLEMENTED = 501;
    const HTTP_BAD_GATEWAY = 502;
    const HTTP_SERVICE_UNAVAILABLE = 503;
    const HTTP_GATEWAY_TIMEOUT = 504;
    const HTTP_VERSION_NOT_SUPPORTED = 505;
    const HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL = 506;
    const HTTP_INSUFFICIENT_STORAGE = 507;
    const HTTP_LOOP_DETECTED = 508;
    const HTTP_NOT_EXTENDED = 510;
    const HTTP_NETWORK_AUTHENTICATION_REQUIRED = 511;

    protected static $labels = [
        Enum_HttpStatusCode::HTTP_CONTINUE => 'Continue',
        Enum_HttpStatusCode::HTTP_SWITCHING_PROTOCOLS => 'Switching Protocols',
        Enum_HttpStatusCode::HTTP_PROCESSING => 'Processing',
        Enum_HttpStatusCode::HTTP_OK => 'OK',
        Enum_HttpStatusCode::HTTP_CREATED => 'Created',
        Enum_HttpStatusCode::HTTP_ACCEPTED => 'Accepted',
        Enum_HttpStatusCode::HTTP_NON_AUTHORITATIVE_INFORMATION => 'Non-Authoritative Information',
        Enum_HttpStatusCode::HTTP_NO_CONTENT => 'No Content',
        Enum_HttpStatusCode::HTTP_RESET_CONTENT => 'Reset Content',
        Enum_HttpStatusCode::HTTP_PARTIAL_CONTENT => 'Partial Content',
        Enum_HttpStatusCode::HTTP_MULTI_STATUS => 'Multi-Status',
        Enum_HttpStatusCode::HTTP_ALREADY_REPORTED => 'Already Reported',
        Enum_HttpStatusCode::HTTP_IM_USED => 'IM Used',
        Enum_HttpStatusCode::HTTP_MULTIPLE_CHOICES => 'Multiple Choices',
        Enum_HttpStatusCode::HTTP_MOVED_PERMANENTLY => 'Moved Permanently',
        Enum_HttpStatusCode::HTTP_FOUND => 'Found',
        Enum_HttpStatusCode::HTTP_SEE_OTHER => 'See Other',
        Enum_HttpStatusCode::HTTP_NOT_MODIFIED => 'Not Modified',
        Enum_HttpStatusCode::HTTP_USE_PROXY => 'Use Proxy',
        Enum_HttpStatusCode::HTTP_TEMPORARY_REDIRECT => 'Temporary Redirect',
        Enum_HttpStatusCode::HTTP_PERMANENTLY_REDIRECT => 'Permanent Redirect',
        Enum_HttpStatusCode::HTTP_BAD_REQUEST => 'Bad Request',
        Enum_HttpStatusCode::HTTP_UNAUTHORIZED => 'Unauthorized',
        Enum_HttpStatusCode::HTTP_PAYMENT_REQUIRED => 'Payment Required',
        Enum_HttpStatusCode::HTTP_FORBIDDEN => 'Forbidden',
        Enum_HttpStatusCode::HTTP_NOT_FOUND => 'Not Found',
        Enum_HttpStatusCode::HTTP_METHOD_NOT_ALLOWED => 'Method Not Allowed',
        Enum_HttpStatusCode::HTTP_NOT_ACCEPTABLE => 'Not Acceptable',
        Enum_HttpStatusCode::HTTP_PROXY_AUTHENTICATION_REQUIRED => 'Proxy Authentication Required',
        Enum_HttpStatusCode::HTTP_REQUEST_TIMEOUT => 'Request Timeout',
        Enum_HttpStatusCode::HTTP_CONFLICT => 'Conflict',
        Enum_HttpStatusCode::HTTP_GONE => 'Gone',
        Enum_HttpStatusCode::HTTP_LENGTH_REQUIRED => 'Length Required',
        Enum_HttpStatusCode::HTTP_PRECONDITION_FAILED => 'Precondition Failed',
        Enum_HttpStatusCode::HTTP_REQUEST_ENTITY_TOO_LARGE => 'Payload Too Large',
        Enum_HttpStatusCode::HTTP_REQUEST_URI_TOO_LONG => 'URI Too Long',
        Enum_HttpStatusCode::HTTP_UNSUPPORTED_MEDIA_TYPE => 'Unsupported Media Type',
        Enum_HttpStatusCode::HTTP_REQUESTED_RANGE_NOT_SATISFIABLE => 'Range Not Satisfiable',
        Enum_HttpStatusCode::HTTP_EXPECTATION_FAILED => 'Expectation Failed',
        Enum_HttpStatusCode::HTTP_I_AM_A_TEAPOT => 'I\'m a teapot',
        Enum_HttpStatusCode::HTTP_MISDIRECTED_REQUEST => 'Misdirected Request',
        Enum_HttpStatusCode::HTTP_UNPROCESSABLE_ENTITY => 'Unprocessable Entity',
        Enum_HttpStatusCode::HTTP_LOCKED => 'Locked',
        Enum_HttpStatusCode::HTTP_FAILED_DEPENDENCY => 'Failed Dependency',
        Enum_HttpStatusCode::HTTP_RESERVED_FOR_WEBDAV_ADVANCED_COLLECTIONS_EXPIRED_PROPOSAL => 'Reserved for WebDAV advanced collections expired proposal',
        Enum_HttpStatusCode::HTTP_UPGRADE_REQUIRED => 'Upgrade Required',
        Enum_HttpStatusCode::HTTP_PRECONDITION_REQUIRED => 'Precondition Required',
        Enum_HttpStatusCode::HTTP_TOO_MANY_REQUESTS => 'Too Many Requests',
        Enum_HttpStatusCode::HTTP_REQUEST_HEADER_FIELDS_TOO_LARGE => 'Request Header Fields Too Large',
        Enum_HttpStatusCode::HTTP_UNAVAILABLE_FOR_LEGAL_REASONS => 'Unavailable For Legal Reasons',
        Enum_HttpStatusCode::HTTP_INTERNAL_SERVER_ERROR => 'Internal Server Error',
        Enum_HttpStatusCode::HTTP_NOT_IMPLEMENTED => 'Not Implemented',
        Enum_HttpStatusCode::HTTP_BAD_GATEWAY => 'Bad Gateway',
        Enum_HttpStatusCode::HTTP_SERVICE_UNAVAILABLE => 'Service Unavailable',
        Enum_HttpStatusCode::HTTP_GATEWAY_TIMEOUT => 'Gateway Timeout',
        Enum_HttpStatusCode::HTTP_VERSION_NOT_SUPPORTED => 'HTTP Version Not Supported',
        Enum_HttpStatusCode::HTTP_VARIANT_ALSO_NEGOTIATES_EXPERIMENTAL => 'Variant Also Negotiates (Experimental)',
        Enum_HttpStatusCode::HTTP_INSUFFICIENT_STORAGE => 'Insufficient Storage',
        Enum_HttpStatusCode::HTTP_LOOP_DETECTED => 'Loop Detected',
        Enum_HttpStatusCode::HTTP_NOT_EXTENDED => 'Not Extended',
        Enum_HttpStatusCode::HTTP_NETWORK_AUTHENTICATION_REQUIRED => 'Network Authentication Required',
    ];
}